package com.kaicom.mymvptest.datasource.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END


/**
 * Entity mapped to table tt_a.
 */
public class AbstractBizEntity  {

    private Long id ; 
    private String backOne = ""; // 备用字段1
    private String backTwo = ""; // 备用字段2
    private String backThree = ""; // 备用字段3
    private String backFour = ""; // 备用字段4

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END




	/** 设置备用字段1 */
    public String getBackOne() {
        return backOne;
    }

	/** 获得备用字段1 */
    public void setBackOne(String backOne) {
        this.backOne = backOne;
    }

	/** 设置备用字段2 */
    public String getBackTwo() {
        return backTwo;
    }

	/** 获得备用字段2 */
    public void setBackTwo(String backTwo) {
        this.backTwo = backTwo;
    }

	/** 设置备用字段3 */
    public String getBackThree() {
        return backThree;
    }

	/** 获得备用字段3 */
    public void setBackThree(String backThree) {
        this.backThree = backThree;
    }

	/** 设置备用字段4 */
    public String getBackFour() {
        return backFour;
    }

	/** 获得备用字段4 */
    public void setBackFour(String backFour) {
        this.backFour = backFour;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
